import { NextResponse, NextRequest } from 'next/server';
import { getRedis } from '@/lib/redis';
import { createClient } from '@supabase/supabase-js';

export async function POST(req: NextRequest) {
  try {
    const { email, otp, type, password, fullName } = await req.json();

    if (!email || !otp || !type) {
      return NextResponse.json({ error: 'Email, OTP, and Type are required' }, { status: 400 });
    }

    const redis = getRedis();
    if (!redis) {
      return NextResponse.json({ error: 'Redis is not configured' }, { status: 500 });
    }

    // Verify OTP in Redis
    const storedOtp = await redis.get(`otp:${email}`);
    if (!storedOtp) {
      return NextResponse.json({ error: 'OTP has expired or was not requested' }, { status: 400 });
    }

    if (String(storedOtp) !== String(otp)) {
      return NextResponse.json({ error: 'Invalid OTP' }, { status: 400 });
    }

    // OTP is correct. Delete it to prevent reuse.
    await redis.del(`otp:${email}`);

    // Generate secure link using Admin SDK
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const siteUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';

    if (type === 'signup') {
      // For signup, create the user directly (bypassing email confirmation)
      const { data: userData, error: userError } = await supabase.auth.admin.createUser({
        email,
        password: password || undefined,
        email_confirm: true,
      });
      if (userError && !userError.message.includes('already exists')) {
        return NextResponse.json({ error: userError.message }, { status: 500 });
      }

      if (userData?.user && fullName) {
        // Create initial profiles
        await supabase.from('profiles').upsert({ id: userData.user.id, full_name: fullName, email });
        await supabase.from('student_profiles').upsert({ user_id: userData.user.id, full_name: fullName, email });
      }
    }

    // Generate the appropriate token link
    let generateType: 'magiclink' | 'recovery' = type === 'recovery' ? 'recovery' : 'magiclink';
    let redirectTo = type === 'recovery' ? `${siteUrl}/update-password` : `${siteUrl}/dashboard`;

    const { data: linkData, error: linkError } = await supabase.auth.admin.generateLink({
      type: generateType,
      email,
      options: {
        redirectTo,
      }
    });

    if (linkError) {
      console.error('Supabase Generate Link Error:', linkError);
      return NextResponse.json({ error: linkError.message }, { status: 500 });
    }

    // Return the action link generated by Supabase (it contains the PKCE/magiclink token)
    return NextResponse.json({ success: true, redirectUrl: linkData.properties.action_link });

  } catch (error: any) {
    console.error('API Verify Custom OTP Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
